[workspace]

[package]
name = "debugger"
version = "0.1.0"
edition = "2021"
authors = ["Tao Liu <ttliu2000@hotmail.com>"]

[[bin]]
name = "riscv_debug_adapter"
path = "src/main.rs"

[dependencies]

 dap = { version = "0.4.1-alpha1" }

#log4rs 
log = "*"
log4rs = "*"

# asm lib
riscv_asm_lib = { path = "../../riscv_asm_lib" }
core_utils = { path = "../../core_utils" }

[build-dependencies]
copy_to_output = "*"